### ISSUE TITLE
ajax-loader-bar.gif is missing from the repository [0.5_bug_fixes]

### ISSUE THREAD

**Issue by ikosmidis** [trackerproject/trackeRapp#1]
@rugeer can you add this file to the correct directory under inst?

**Comment by rugeer** [comment]
@ikosmidis I added the file, but I am not able to make it work, the app is not able to load the gif with the following error: Failed to load resource: the server responded with a status of 404 (Not Found). The source code app itself does not work (https://github.com/daattali/advanced-shiny/tree/master/busy-indicator), where the gif does not display. I tried moving the file to various locations, but I am not able to figure out why the app is not able to load the file.

**Comment by rugeer** [comment]
@ikosmidis we can easily just comment out that line of code and avoid this issue. The calculation of the new graph is reasonably quick, so it seems that its not necessary to display the gif.

**Comment by rugeer** [comment]
@ikosmidis for now I have disabled the gif, you can see in the latest git [commit](https://github.com/trackerproject/trackeRapp/commit/4113a3c04ce1ea7b32657df06bf9e5ae71fab5d6). However, I have kept the gif file, in case you wanted to try. If you are happy with removing it, we can then remove the gif file and close this issue.

**Comment by ikosmidis** [comment]
OK let's keep the interface without the loader gif, but let's keep it in the tree for now. Cheers -Y
