### ISSUE TITLE
Import processed data (rda) should be "(rds)"

### ISSUE THREAD

**Issue by krissen** [trackerproject/trackeRapp#47]
Header says import... rd*a* but file picker only accepts rd*s*. In actual fact, as far as I can rell `.rda`would be fine, as would `.RData` (as long as it contains trackeRdata).

Suggestion: keep title "Import processed data (rda)" but make file picker accept common varieties of file extensions (at least `.rds`, `.rda`, `.RData`).

**Comment by ikosmidis** [comment]
That's a typo. Now fixed in develop branch.

.rda and .Rdata will never be supported as serialization of a single object is what we need.  Consult R's help pages for the differences between `.rds` and `.rda/.Rdata` (e.g. `?saveRDS` `?save`)
