### ISSUE TITLE
Add raw data through directory, not only individual files

### ISSUE THREAD

**Issue by krissen** [trackerproject/trackeRapp#48]
There only seems to be an option to add raw files or processed data, not directory of raw files. 

I actually tried adding 2700 files through the file picker (select first; scroll down, shift-click last; all are selected), but it doesn't seem to work. At the most, I've been able to add 600 files. No more seem to be accepted. Not sure if that is due to the file picker or trackeRapp.

**Comment by ikosmidis** [comment]
For directory just "Add raw data (gpx tcx json db3)" and then select everything in the directory. 

Not sure why 2700 files are not supported. I added this to the tests for next version.

For now, try doing them in batches of 200 (and I'd recommend that) for now though trackeRapp's workflow:

Add raw data -> Select first 200 -> Wait for the interface to process those -> Add raw data -> Select next 200  and so on.

Download the processed data file every now and then to avoid data loss if browser shiny crashes.
